baseURL = "https://suryansh011.github.io/"
languageCode = "en-us"
title = "Suryansh Shishodia"
theme = "ink-free"
paginate = 5

copyright = "© Suryansh Singh Shishodia"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
  subtitle = "computers and more"

  # Optional 64x64 avatar image.
  #avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

  featherIconsCDN = false

  # Enable a table of contents
  toc = true

  # Max tags
    maxTags = 7

  # Define words per minute to approximate reading time
  wpm = 250

  # Stupid footers :)
  footers = [ 
    "What Tiger King can teach us about x86 Assembly",
    "10 Reasons why gcc SHOULD be re-written in JavaScript - You won't believe #8!"
  ]

  # Github base url
#    github = "https://github.com/suryansh011/"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/suryansh011/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
